[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sms-spam-detection"
dependencies = [
    "streamlit>=1.28.0",
    "transformers>=4.21.0",
    "torch>=1.9.0",
    "numpy>=1.21.0",
    "scikit-learn>=1.0.0",
    "pandas>=1.3.0",
]
